### ISSUE TITLE
Symfony 7.0

### ISSUE THREAD

**Issue by ThibaultPelloquin** [eckinox/tinymce-bundle#9] opened 2023-12-04 20:27 UTC
Hi!

Could you upgrade composer.json to make this bundle suitable to Symfony 7 please ? ^^

Thanks a lot :-)

**Comment by EmilePerron** [comment] 2023-12-19 13:39
Hi folks!

I just got granted access to manage this repository once more, so I can take care of this now. 
I will try to add support for Symfony 7 sometimes before the end of the week.

Thanks for your patience (and apologies for the delays!)

**Comment by EmilePerron** [comment] 2023-12-24 01:07
Hi folks!

I just worked on a small PR for this, which has been released as a beta under version `v1.1.0-beta`.
I tested it locally using projects running Symfony 5.4, 6.3 and 7.0, and have not experienced any problems.

Please try it out and let me know if everything works as intended on your end.

If all goes well, I will merge this into the main branch and publish a stable release.

Cheers!

**Comment by remicorso** [comment] 2024-01-31 10:47
Hello Emile,

Do you have any information about this update ?

Thanks.

**Comment by EmilePerron** [comment] 2024-01-31 13:49
Hi @remicorso,

I have not gotten any feedback on this, positive or negative, and I since went on paternity leave so I have little time to conduct further tests myself.

If you, @ThibaultPelloquin or anyone else who uses the package in their project(s) can try out the beta release I mentioned above (`v1.1.0-beta`) and indicate that all works well for them, I’d be happy to merge this and to publish a stable release.

Cheers! :)

**Comment by SolidGlenn** [comment] 2024-02-01 14:05
Please do merge this.
So far, the beta works for me

**Comment by EmilePerron** [comment] 2024-02-02 14:11
Support for Symfony 7 has just been released in v1.1.0. Please upgrade and let us know of any issues you encounter by creating a new issue in this repo.

Cheers! 🎉

**Closed as completed by EmilePerron** 2024-02-02 14:11 UTC
